name: CI Pipeline

on: 
    push 
jobs: 
    install: 
        run-on: unbuntu-latest 
        steps: 
            - name: checkout code 
            - uses: actions/checkout@v3
            - name: Step up Node.js
            - uses: actions/setup-node@v3
            with:
                node-version: '18'
            name: install dependencies
            run: npm install

